# SwiftLint configuration for ClaudeMeter
# https://github.com/realm/SwiftLint

# Paths to include
included:
  - ClaudeMeter
  - ClaudeMeter-iOS
  - ClaudeMeterWidgets
  - ClaudeMeterKit/Sources
  - ClaudeMeterTests
  - ClaudeMeter-iOSTests

# Paths to exclude
excluded:
  - build
  - .build
  - DerivedData
  - ClaudeMeterKit/.build
  - ClaudeMeterUITests
  - ClaudeMeter-iOSUITests

# Rules to disable (conflict with SwiftUI patterns)
disabled_rules:
  - trailing_comma # SwiftUI arrays often have trailing commas
  - todo # Allow TODOs during development
  - orphaned_doc_comment # SwiftUI previews can have detached comments

# Optional rules to enable
opt_in_rules:
  - empty_count # Use .isEmpty instead of .count == 0
  - first_where # Use .first(where:) instead of .filter().first
  - identical_operands # Catch logic errors like x == x
  - force_unwrapping # Warn on force unwrapping (not error)
  - implicit_return # Explicit returns for clarity
  - vertical_whitespace_closing_braces # Clean closing braces
  - closure_end_indentation # Consistent closure indentation

# Analyzer rules (run via `swiftlint analyze`)
analyzer_rules:
  - unused_import

# Rule configurations

# Line length - increased for SwiftUI modifier chains
line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

# Function body length - SwiftUI ViewBuilders can be long
function_body_length:
  warning: 100
  error: 200

# Closure body length
closure_body_length:
  warning: 50
  error: 100

# Type body length - SwiftUI Views can be substantial
type_body_length:
  warning: 400
  error: 600

# File length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

# Nesting - SwiftUI nested types are common
nesting:
  type_level: 3
  function_level: 3

# Identifier name
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
    - k

# Large tuple
large_tuple:
  warning: 4
  error: 5

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Force cast - warning only (needed for some SwiftUI patterns)
force_cast: warning

# Force try - warning only
force_try: warning

# Custom rules
custom_rules:
  # Discourage print statements in production code
  no_print_statements:
    name: "No Print Statements"
    regex: "\\bprint\\s*\\("
    message: "Prefer os_log or Logger over print statements"
    severity: warning
    excluded: ".*Tests?\\.swift$"
